CREATE OR REPLACE PROCEDURE CANCELS_TEAM1
AS TICK_ID NUMBER;
BEGIN 
 TICK_ID := &TICKET_ID;

        DBMS_OUTPUT.PUT_LINE( TICK_ID );
        UPDATE FLIGHTS_TEAM1 SET AVAILABLE_SEATS = AVAILABLE_SEATS + 1 
        WHERE FLIGHT_ID IN (SELECT FLIGHT_ID FROM BOOKINGS_TEAM1 WHERE TICKET_ID = TICK_ID);
        DELETE FROM Bookings_Team1 WHERE TICKET_ID = TICK_ID;
        IF SQL%FOUND THEN
            DBMS_OUTPUT.PUT_LINE('CANCELLED');
        ELSE
            DBMS_OUTPUT.PUT_LINE('PLEASE ENTER VALID TICKET ID');
        END IF;
END;

EXEC CANCELS_TEAM1;
